# theme: Cayman
remote_theme: dxiai/dxiai-theme

title: dxi.ai

paginate: 5
paginate_path: "/blog/page:num"

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      show_sidebar: true